<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Toucan - Create student</title>
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="create-student container">
            <form method="POST" action="create" id="create-student-form" class="well form-horizontal">
                <div class="form-group">
                    <label class="col-md-4 control-label">Full Name</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-user"></i>
                            </span>
                            <input  name="name" placeholder="Full Name" class="form-control" type="text"
                                    value = <?php echo (isset($student['name']) ? $student['name'] : ''); ?> >
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">E-Mail Address</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-envelope"></i>
                            </span>
                            <input  name="email" placeholder="E-Mail Address" class="form-control" type="text"
                                    value = <?php echo (isset($student['email']) ? $student['email'] : ''); ?> >
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">School</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="glyphicon glyphicon-list"></i>
                            </span>
                            <select name="school" class="form-control selectpicker">
                                <option value="" <?php echo (!isset($student) ? 
                                    'selected= `selected`' : '') ?>>Please select a school</option>
                                <?php if(isset($schools)) {
                                    for($i = 0; $i < sizeof($schools); $i++) {
                                    echo "<option value=" . $schools[$i][0] . " " . 
                                        (isset($student) && isset($student['school']) 
                                            && $student['school'] == $schools[$i][0] ? 
                                            "selected= `selected`" : "") . ">" . 
                                                $schools[$i][0] . 
                                        "</option>";
                                    }
                                } ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="alert alert-error" role="alert" id="error_message" 
                    <?php if(!isset($error_message)) echo "style='display:none'"; ?> >Error 
                    <i class="glyphicon glyphicon-thumbs-down"></i> 
                    <?php if(isset($error_message)) echo $error_message; ?>
                </div>
                <div class="form-group">
                  <label class="col-md-4 control-label"></label>
                    <div class="col-md-4">
                        <button type="submit" class="btn btn-warning">Send 
                            <span class="glyphicon glyphicon-send"></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js">
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/form-validation.js"></script>
    </body>
</html>
